name: Keep Streamlit App Awake

# Schedule to run the workflow
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Delay
        id: delay
        run: |
          # Generate a delay between 0 and 86400 seconds (up to 24 hours)
          RANDOM_DELAY=$((RANDOM % 86400))
          echo "Waiting for $RANDOM_DELAY seconds before pinging..."
          sleep $RANDOM_DELAY
          echo "::set-output name=delay::$RANDOM_DELAY"

      - name: Ping App
        run: |
          # After the delay, send a ping request to the app
          curl -X GET "https://youtubesenti.streamlit.app" || true
        if: ${{ steps.random_delay.outputs.delay }}
